services:
  mongodb:
    image: mongo:8
    container_name: user-management-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5

  user-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongodb:27017
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data:
  